appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: YGXJaDwzi/UsEJ/6cwc+xQSKbmEXSRbAP0LaGrRKYzOAeoOr5OE/6dxXC3bl2oc4oNdRazovA+Qgtl3C1yWQEbc1dAt2dE2t/6MTPs08K5FllceKKbyw2769iZQOG14AtopM07OYSuDAoxNwnAV245Wga/0EDtCSuGCgC/PdJAMw0EEhO6fC+nu6M0gxHAevq2PLqZ18VNnhrCWQhUQnndAF1etsVUxUl+H0QXZUPS6tC79/Mal3EZbQsnI4PzuQAi1tU5JP/JwilR7/pXvNJ1D04W7CSmlYBQAvJhhMLpXFc8LCPMJxYKJ0LdTa1g/SfH9w7+F6uqj93c8OIzgDlyujwj/w47gU9Nxg93IAiN7mDvRJkyW6EeqFC2uxpqMpBLj6xPKk0Gss8hlLRAps0uvnUe8Dl4EnVrcZsa0u1SlkmTVIpErkqI4dzHl5CUKsWiwkj6r0VvofZy1aNBkcqaZ+eHTTcY366vqD/DoxhCYUpDyj1M7qBcFCzw6rgSfN0/iK3XA69o8P+dJ9/rXiNbWnQy3f4HWUW8vkb9qeM5qvszey6qNtiZ7NzzM451DXcls1voyk74pOibdtyUmvbQ/iWxwqI/q4adJ6QBoL80KqelDvpbqjVFhDh8mukJd2B5sC1mxk3+Dpdem6pGZn79fngRpNnUe0aYGCHTe9E/8=}
provider:
  win: azure
bot:
  automerge: true
